# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Courses"
url = "courses/"
weight = 2

[[main]]
name = "Resources"
url = "resources/"
weight = 3

[[main]]
name = "Research skills"
url = "research-skills"
weight = 4

# [[main]]
# name = "Blog"
# url = "blog/"
# weight = 50

# [[main]]
# weight = 100
# name = "Pages"
# hasChildren = true

#   [[main]]
#   parent = "Pages"
#   name = "Blog Details"
#   url = "blog/post-1/"
#   weight = 1

#   [[main]]
#   parent = "Pages"
#   name = "Terms & Conditions"
#   url = "terms-and-conditions/"
#   weight = 7
  
# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 200


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4
