# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 2
name = "Study design"
url = "study-design/"

[[main]]
name = "Measures"
weight = 3
hasChildren = true

  [[main]]
  parent = "Measures"
  name = "Overview"
  url = "measures/"
  weight = 1

  [[main]]
  parent = "Measures"
  name = "Phonetics"
  url = "measures/phonetics/"
  weight = 2

[[main]]
name = "Data analysis"
url = "analysis/"
weight = 4

[[main]]
name = "Skills"
url = "skills"
weight = 5

[[main]]
name = "Software"
url = "software/"
weight = 6

# [[main]]
# name = "Courses"
# url = "courses/"
# weight = 7

[[main]]
name = "Support"
url = "support/"
weight = 8

# [[main]]
# name = "Blog"
# url = "blog/"
# weight = 50

# [[main]]
# weight = 100
# name = "Pages"
# hasChildren = true

#   [[main]]
#   parent = "Pages"
#   name = "Blog Details"
#   url = "blog/post-1/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4
