---
title: "LEL Statistical Training Workshops (STeW)"
editor: visual
---

The Linguistics and English Language **Statistical Training Workshops** (**STeW**) is a series of workshops that runs throughout the academic year and is aimed at students and staff who would like to advance their statistical knowledge and skills.

On this page you can find information on the current plan for the a.y.
2024-25.
Attending requires you register and registration links are sent out via email at the beginning of each semester.
Further workshops might be added later during the year.

Most workshops are recorded and can be watched on the [LEL Quantitative Methods channel](https://media.ed.ac.uk/channel/LEL%2BQuantitative%2BMethods/308657412) on the UoE Media Hopper Create.

If you have any question, you can get in touch with Dr Stefano Coretta.

## 2025-26

### Semester 1

::: callout-tip
#### Quantitative Methods in LEL (QML)

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | First teaching term                                                                                                                                                                     |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | See timetable on DRPS.                                                                                                                                                                  |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                            |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This is the flagship stats course of the Linguistics and English Language department. It covers the basics of statistics in R and PhD Students are particularly encouraged to audit it. |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                                                                   |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://uoelel.github.io/qml/>                                                                                                                                                         |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

### Semester 2

::: callout-tip
#### Open Research practices in linguistics

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | TBD                                                                                                                                                                                      |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                             |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | A primer for Open Research practices in linguistics for all researchers/scholars. This workshop will cover practices that can be applied to qualitative and quantitative research alike. |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     |                                                                                                                                                                                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     |                                                                                                                                                                                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Causal inference: correlation *is* causation

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | TBD                                                                                                                                                                                                                                                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | TBD                                                                                                                                                                                                                                                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | In this workshop, you will learn the basics of causal inference and how regression models can help estimate causal effects. Causal inference is based on the theory of Directed Acyclic Graphs (DAGs), which will be introduced with examples from linguistics. |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Familiarity with regression models is necessary to understand the application of DAG theory to data analysis, but anyone with at least some prior statistical background is welcome to join.                                                                    |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     |                                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     |                                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

## Previously

::: callout-tip
#### intRo: Data visualisation with R

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | 18 December 2022                                                                                                                             |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This is an introduction to R and data visualisation for absolute beginners. If you want to learn R for the first time, this is a good start. |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                        |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://intro-rstats.github.io>                                                                                                             |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Day 1](https://media.ed.ac.uk/media/intRoA+Day+1/1_aah5ninw), [Day 2](https://media.ed.ac.uk/media/intRoA+Day+2/1_196jx1qj)                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### Mindless statistics and the "null ritual"

+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Thursday 1 May 2025                                                                                                                                                                                                                                                                                                                                                                                                             |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢🟠🔴 Any level                                                                                                                                                                                                                                                                                                                                                                                                                |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | In this workshop we will go through bad statistical practices that are common even among experienced researchers and how to avoid them. In particular, we will talk about the "null ritual", which is a invalid approach to frequentist statistics commonly used in research. Most of the content of the workshop will be drawn from Gigerenzer's [Mindless Statistics](https://www.doi.org/10.1016/j.socec.2004.09.033) paper. |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Some familiarity with frequentist statistics is useful but not necessary. This workshop is thought for both beginners and experienced researchers or students, whether they normally use quantitative, qualitative or mixed methods.                                                                                                                                                                                            |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/null-ritual/>                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Introduction to Bayesian Linear Models

+-------------------+----------------------------------------------------------------------------------------+
| **Date**          | Thursday 26 October 2023                                                               |
+-------------------+----------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                           |
+-------------------+----------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                        |
+-------------------+----------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnBayes/>                                         |
+-------------------+----------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/LEL+Bayesian+Linear+Models+2023+Sem+1/1_slt88gj6) |
+-------------------+----------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Including random effects in Bayesian Linear models with `brm()`

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Thursday 16 May 2024                                                                                                                     |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                             |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This workshop is targeted especially to **MSc students** who have attended the **QML course**.                                           |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Anybody who has attended the previous Bayesian workshops or who has experience with basic linear models with `brm()` is welcome to join. |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://uoelel.github.io/brm-group/>                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/STeW+-+Including+random+effects+in+Bayesian+Linear+models+with+brm%28%29/1_5tz3sfdl)                |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Generalised Additive Mixed Models (GAMMs)

+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Thursday 18 April 2024                                                                                                                     |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                            |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | GAMMs are useful to analyse historical data, time-series data or data that could have non-linear effects (like language development data). |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | It assumes some familiarity with linear models fitted with `lmer()`/`glmer()` or `brm()`.                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnGAM/>                                                                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/learnGAMA+GAMMs+workshop+for+LEL+%282023%29/1_qsbcwusm) (recording of previous run of the workshop)   |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Prospective power analyses for frequentist regression models

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Wednesday 26 March 2025                                                                                                                                                                                                                                                                                                                                                                                                                      |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                                                                                                                                                                                                                                                                                                                              |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | You will learn how to perform prospective power analyses for regression/linear models fitted with the frequentist lme4 package. Power analyses are a necessary (albeit always neglected) component of frequentist analyses, since they help the researcher determine the required sample size. Much of the replicability crisis we are facing is due to lack of statistical power (aka low sample sizes) in virtually all published studies. |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions.                                                                                                                                                                                                                                                                                               |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/proPower/>                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/proPower%3A+Prospective+power+analyses+for+frequentist+regression+models/1_bgsbzz7a)                                                                                                                                                                                                                                                                                                                    |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-important
#### Ordinal models for Likert/rating-scale data

+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Thursday 23 January 2025                                                                                                                                                                                                                                                                        |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                                                                                                                                                                                    |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🔴 Advanced                                                                                                                                                                                                                                                                                     |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | In this workshop you will learn how to model data from Likert/rating scales, such as the ones commonly used in developmental and psycho- linguistics using ordinal models.                                                                                                                      |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions. While a background in Bayesian inference is useful, the workshop will explain the basics of Bayesian inference in the context of ordinal models. |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnOrd/>                                                                                                                                                                                                                                                    |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/learnOrd%3A+Ordinal+regression+models+for+Likert+rating+scales+data/1_im4onksw/308657412)                                                                                                                                                                  |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-important
#### Bayesian Priors in Linear Models

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | Thursday 22 February 2024                                                                                                                                                                                                                                            |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**          | 15.00--17.00                                                                                                                                                                                                                                                         |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🔴 Advanced                                                                                                                                                                                                                                                          |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with Bayesian Linear Models including Random Effects and/or have attended the *Introduction to Bayesian Linear Models* workshop. This is **not** suitable for students who have only attended the QML course (see below for dedicated workshop). |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnBayes/> (Session 2)                                                                                                                                                                                                           |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | Unfortunately I forgot to record this, but you can watch the following videos from [another workshop](https://learnb4ss.github.io) to learn about priors (these videos go into much more detail!).                                                                   |
|                   |                                                                                                                                                                                                                                                                      |
|                   | -   [learnB4SS — 03 Application to Regression II: Priors and Bayesian Updating (Part I)](https://media.ed.ac.uk/media/learnB4SS+%E2%80%94+03+Application+to+Regression+IIA+Priors+and+Bayesian+Updating+%28Part+I%29/1_vl395dhg)                                     |
|                   |                                                                                                                                                                                                                                                                      |
|                   | -   [learnB4SS — 03 Application to Regression II: Priors and Bayesian Updating (Part II)](https://media.ed.ac.uk/media/learnB4SS+%E2%80%94+03+Application+to+Regression+IIA+Priors+and+Bayesian+Updating+%28Part+II%29/1_6e35jw34)                                   |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::
