---
title: "Support"
---

There are different support channels for Hons/MSc/PhD students who are writing their dissertation, and researchers/staff who are seeking help with any aspect of quantitative data analysis.

## General support

As a general guideline aimed at students, supervisors, and staff, we have compiled a checklist that covers all the main aspects of quantitative analyses.

You can use the checklist as a template to think about your quantitative analysis plan at the early stages of your dissertation/research project.

```{=html}
<a class="btn btn-primary" href="./extra/analysis-checklist.html" role="button">Go to checklist</a>
```

## Honours and MSc students

If you are a student writing your Honours or MSc dissertation in Linguistics and English Language and you are looking after help with your quantitative data analysis/statistics, you can book an appointment with Dr Stefano Coretta.
Note that a university account is required for booking.

```{=html}
<a class="btn btn-primary" href="https://outlook.office365.com/owa/calendar/Stefanosofficehours@uoe.onmicrosoft.com/bookings/" role="button">Book an appointment</a>
```

## Consultation for PhD students, postdocs and staff

Many of the issues arising during the data analysis stage can be prevented by planning your analysis while designing the study and ahead of data collection.
<u>**We strongly recommend you to work out your quantitative data analysis plan in details as early as possible.**</u> This expedient will save you time later on.

PhD students, postdoc researchers and staff can get in touch with Dr Stefano Coretta, or directly book an appointment with Stefano via the link below (a university account is required).

```{=html}
<a class="btn btn-primary" href="https://outlook.office365.com/owa/calendar/Stefanosofficehours@uoe.onmicrosoft.com/bookings/" role="button">Book an appointment</a>
<br><br>
```

Help is offered for the following areas:

-   Study design and operationalisation of research hypothesis.
-   Data wrangling and visualisation.
-   Statistical modelling.
-   Research data management (including Data Management Plans).
-   Reporting.
-   Open Science practices.

## Statistical service for staff

Dr Stefano Coretta is available as a collaborator on projects or papers requiring the planning and execution of quantitative and statistical analyses.

Interested postdocs or staff should contact Stefano for enquiries.
